### ISSUE TITLE
linkArr is not defined

### ISSUE THREAD

**Issue by tunisj** [Cillian-Collins/dirscraper#3]
Output:
Traceback (most recent call last):
  File "dirscraper.py", line 39, in <module>
    for link in linkArr:
NameError: name 'linkArr' is not defined

**Comment by tunisj** [comment]
looks like the pull request from @jaikishantulswani fixes the issue

**Comment by Cillian-Collins** [comment]
I already made a push to fix this, I noticed it after my last update that I had accidentally removed.

Should be working now..
