### ISSUE TITLE
Add try/catch for requests.exceptions.MissingSchema

### ISSUE THREAD

**Issue by BBerastegui** [Cillian-Collins/dirscraper#6]
Hey !

How about adding a try/catch to add it some reliability/flexibility so we can pass domains without schema i.e.: `google.com` instead of `http://google.com` or `https://google.com`.

To avoid: 

```requests.exceptions.MissingSchema: Invalid URL 'REDACTED/': No schema supplied. Perhaps you meant http://REDACTED/?```

Cheers !

Related: https://stackoverflow.com/questions/35293174/python-requests-module-http-and-https-requests

**Comment by Cillian-Collins** [comment]
Done, thanks for the suggestion!
