### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Teicu** [Cillian-Collins/dirscraper#7]
any help to solve the following issue? Thank you 

I'm using MacOS

Output:
Traceback (most recent call last):
  File "dirscraper.py", line 37, in <module>
    soup = BeautifulSoup(r.text, 'html5lib')
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by Teicu** [comment]
sorry, works fine using python3 

Cheers

**Comment by Cillian-Collins** [comment]
Sorry for the late response.

The error in question which you posted is related to our html5lib. You should pip install it.
On a side note, it's actually a good idea to use lxml instead, you can modify the source code to use that if you'd like. It'll increase speeds significantly.
